#
# File ini berisi flag konfigurasi untuk menyesuaikan situs Anda
#

# Nama situs Anda (ditampilkan di tajuk)
nama: Nama Anda

# Bio atau deskripsi singkat (ditampilkan di tajuk)
deskripsi: Pengembang Web dari Suatu Tempat

# URL avatar atau foto profil Anda (Anda bisa menggunakan foto profil GitHub Anda)
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

#
# Bendera di bawah ini adalah opsional
#

# Termasuk ikon di footer untuk setiap nama pengguna yang Anda masukkan
tautan footer:
  menggiring bola:
  e-mail:
  facebook:
  flickr:
  github: barryclark / jekyll-now
  Instagram:
  linkedin:
  pinterest:
  rss: # cukup ketik apa saja di sini untuk ikon RSS yang berfungsi
  twitter: jekyllrb
  stackoverflow: # profil stackoverflow Anda, mis. "users / 50476 / bart-kiers"
  youtube: # channel / <your_long_string> atau pengguna / <user-name>
  googleplus: # apa pun di nama pengguna profil Anda yang muncul setelah plus.google.com/


# Masukkan nama pendek Disqus Anda (bukan nama pengguna Anda) untuk mengaktifkan komentar pada posting
# Anda dapat menemukan nama pendek Anda di halaman Pengaturan akun Disqus Anda
disqus:

# Masukkan kode pelacakan web Google Analytics Anda (mis. UA-2110908-2) untuk mengaktifkan pelacakan
google_analytics:

# URL situs web Anda (mis. Http://barryclark.github.io atau http://www.barryclark.co)
# Digunakan untuk Sitemap.xml dan umpan RSS Anda
url:

# Jika Anda meng-hosting situs Anda di repositori Proyek di halaman GitHub
# (http://workhome.github.io/workhome)
# dan BUKAN repositori Pengguna Anda (http://workhome.github.io)
kemudian tambahkan dalam baseurl di sini, seperti ini: "/ workhome"
baseurl: ""

#
# !! Anda tidak perlu mengubah flag konfigurasi di bawah ini !!
#

permalink: /: title /

# Pelepasan Jekyll Sekarang yang Anda gunakan
versi: v1.2.0

# Jekyll 3 sekarang hanya mendukung Kramdown for Markdown
kramdown:
  # Gunakan markdown rasa GitHub, termasuk blok kode berpagar backtick tiga
  input: GFM
  # Jekyll 3 dan GitHub Pages sekarang hanya mendukung rouge untuk penyorotan sintaksis
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Gunakan sintaksis pygments yang ada menyoroti css
    css_class: 'highlight'

# Setel direktori Sass partials, karena kami menggunakan @import
kelancangan:
  style:: diperluas # Anda mungkin ingin memperkecil menggunakan: dikompresi

# Gunakan plug-in berikut
permata:
  - jekyll-sitemap # Buat sitemap menggunakan permata sitemap Jekyll resmi
  - jekyll-feed # Buat feed Atom menggunakan permata feed Jekyll resmi

# Kecualikan file-file ini dari situs produksi Anda
mengecualikan:
  - Gemfile
  - Gemfile.lock
  - LISENSI
  - README.md
  - CNAME
